language: java
jdk:
  - openjdk17 # java8이면, openjdk8

branches:
  only:
    - master # git default 브런치를 등록한다. (ex. master)

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r Cemtoo2-webservice *
  - mkdir -p deploy
  - mv Cemtoo2.zip deploy/Cemtoo2.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webbucket # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: postwoong/Cemtoo2
      branch: master

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - postwoong@naver.com