spring:
  profiles:
    active: local # ?? ?? ??

# local ??

server:
  port: 8080

# ?? ??
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8080

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8080